<template x-if="!parseInt(catalogData.moduleConfig?.lazyloadMode || 0)">
    <div class="field limiter">
        <label class="label" for="limiter">
            <span><?= __('Show') ?></span>
        </label>
        <div class="control">
            <select id="limiter"
                    class="limiter-options"
                    x-model="catalogData.pageSize"
                    @change="catalogToolbarLimiter.changePageSize()">

                <template x-for="size in catalogToolbarLimiter.getAvailablePages()" :key="size">
                    <option :value="size" x-text="size"></option>
                </template>
            </select>
        </div>
        <span class="limiter-text"><?= __('per page') ?></span>
    </div>
</template>
