<template x-if="!parseInt(moduleConfig.lazyloadMode)">
    <div class="pages" x-show="getTotalPages() > 1">
        <strong class="label pages-label"><span><?= __('Page') ?></span></strong>
        <ul class="items pages-items">

            <template x-if="currentPage > 1">
                <li class="item pages-item-previous">
                    <a class="action previous" href="#" @click.prevent="changePage(currentPage - 1)" title="<?= __('Previous') ?>">
                        <span class="label"><?= __('Page') ?></span>
                        <span><?= __('Previous') ?></span>
                    </a>
                </li>
            </template>

            <template x-for="(page, index) in getFramePages()" :key="index">
                <li class="item" :class="{ 'current': page.isCurrent }">

                    <template x-if="page.type === 'jump'">
                        <span class="page">...</span>
                    </template>

                    <template x-if="page.type === 'page' && page.isCurrent">
                        <strong class="page">
                            <span class="label"><?= __('You are currently reading page') ?></span>
                            <span x-text="page.number"></span>
                        </strong>
                    </template>

                    <template x-if="page.type === 'page' && !page.isCurrent">
                        <a href="#" class="page" @click.prevent="changePage(page.number)">
                            <span class="label"><?= __('Page') ?></span>
                            <span x-text="page.number"></span>
                        </a>
                    </template>

                </li>
            </template>

            <template x-if="currentPage < getTotalPages()">
                <li class="item pages-item-next">
                    <a class="action next" href="#" @click.prevent="changePage(currentPage + 1)" title="<?= __('Next') ?>">
                        <span class="label"><?= __('Page') ?></span>
                        <span><?= __('Next') ?></span>
                    </a>
                </li>
            </template>

        </ul>
    </div>
</template>
