<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter">
        <span><?= __('Sort By') ?></span>
    </label>

    <select id="sorter"
            data-role="sorter"
            class="sorter-options"
            x-model="catalogData.currentSortField"
            @change="catalogToolbarSorter.changeSort()">
        <template x-for="option in catalogData.pageConfig.availableSortList" :key="option.value">
            <option :value="option.value"
                    x-text="option.label"
            </option>
        </template>
    </select>

    <a href="#"
       class="action sorter-action"
       :class="catalogToolbarSorter.getSortDirectionClass()"
       :title="catalogToolbarSorter.getSortDirectionTitle()"
       @click.prevent="catalogToolbarSorter.changeDirection($event)">
        <span x-text="catalogToolbarSorter.getSortDirectionTitle()"></span>
    </a>
</div>
