<div>
    <div class="reservation-messages"></div>
    <form
        id="form-validate"
        method="post"
        autocomplete="off"
        data-mage-init='{"validation":{}}'>
        <label><?= __('Ім’я') ?> *</label>
        <input type="text" name="name" class="input-text required-entry">

        <label><?= __('Email') ?> *</label>
        <input type="text" name="email" class="input-text required-entry validate-email">

        <label><?= __('Телефон') ?></label>
        <input type="text" name="phone" class="validate-phoneLax">

        <button type="submit" class="action primary">
            <?= __('Submit') ?>
        </button>
    </form>
</div>

<script>
    require([
        'jquery',
        'mage/mage'
    ], function ($) {
        function getSelectedProductId() {
            var swatchRenderer = $('[data-role=swatch-options]')
                .data('mage-SwatchRenderer');
            if (swatchRenderer && swatchRenderer.getProduct()) {
                return swatchRenderer.getProduct(); // simple
            }
            return $('input[name="product"]').val(); // configurable
        }

        var $form = $('#form-validate');
        $form.mage('validation', {});
        $('#form-validate').on('submit', function (e) {
            e.preventDefault();
            var $form = $(this);
            if (!$form.validation('isValid')) {
                return;
            }

            var data = $form.serialize();
            data += '&qty=' + $('#qty').val();
            data += '&product_id=' + getSelectedProductId();

            $.ajax({
                url: 'perspectivereservation/reservation/order',
                type: 'POST',
                data: data,
                dataType: 'json',
                success: function (response) {
                    if (!response.success) {
                        $('.reservation-messages').html(
                            '<div class="message error">' +
                            response.message +
                            '</div>'
                        );
                        return;
                    }

                    console.log(response);
                    $('#reservation-modal').modal('closeModal');
                },
                error: function () {
                    console.log('Error');
                }
            });
        });
    });
</script>
