<?php
/** @var \Perspective\ProductReservation\ViewModel\FormData $viewModel */
$viewModel = $block->getData('viewModel');
?>
<div>
    <div class="reservation-messages"></div>
    <form
        id="form-validate"
        method="post"
        autocomplete="off">
        <label><?= __('Ім’я') ?> *</label>
        <input type="text" name="name" class="input-text required-entry validate-no-html-tags" value="<?= $viewModel->getCustomerFirstName() ?>">

        <label><?= __('Email') ?> *</label>
        <input type="text" name="email" class="input-text required-entry validate-email " value="<?= $viewModel->getCustomerEmail() ?>">

        <label><?= __('Телефон') ?></label>
        <input type="text" name="phone" class="validate-phoneLax" value="<?= $viewModel->getCustomerPhone() ?>" >

        <button type="submit" class="action primary">
            <?= __('Submit') ?>
        </button>
    </form>
</div>
