<!-- отступ -->
<?php

?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Memasik')) ?></span>
    </div>
    <div class="admin__page-section-content">
        TESTTESTTESTTESTTEST
        <!--react component
            render memes list with select one
            ajax request to save selected into quote
         -->
    </div>
</section>
