<div id="testik_12212155"
     data-bind="scope:'voting-scope-testik_12212155'"
     class="testik-item"
>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#testik_12212155": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "voting-scope-testik_12212155": {
                            "component": "Perspective_AsyncCatalog/js/view/filters"
                        }
                    }
                }
            }
        }
    </script>
</div>
