<?php
use Magento\Framework\View\Element\Template;
/** @var Template $block */

$renderers = [];
$layout = $block->getLayout();
$rendererNames = $layout->getChildNames('catalog.root.listing.render-types') ?: [];

foreach ($rendererNames as $name) {
    $child = $layout->getBlock($name);
    if ($child && $modeCode = $child->getData('renderer_code')) {
        $renderers[$modeCode] = $name;
    }
}
?>

<?php foreach ($renderers as $code => $blockName): ?>
    <template x-if="catalogToolbarViewmode.currentMode === '<?= $code ?>'">
        <div class="mode-wrapper-<?= $code ?>">
            <?= $block->getLayout()->renderElement($blockName) ?>
        </div>
    </template>
<?php endforeach; ?>
