<?php
use Magento\Framework\View\Element\Template;
use Perspective\AsyncCatalog\ViewModel\CatalogCategory;
/** @var Template $block */
/** @var CatalogCategory $viewModel */
$viewModel = $block->getData('viewModel');

$pageConfig = $viewModel->getPageConfig();
$test = 1;
?>

<div id="testik_122121"
     data-bind="scope:'voting-scope-testik_122121'"
     class="testik-item"
>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#testik_122121": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "voting-scope-testik_122121": {
                            "component": "Perspective_AsyncCatalog/js/view/products",
                            "pageConfig": <?= /* @noEscape */ json_encode($pageConfig) ?>
                        },
                        "product-listing-toolbar": {
                            "component": "Perspective_AsyncCatalog/js/view/toolbar"
                        }
                    }
                }
            }
        }
    </script>
</div>
