<div id="testik_122121"
     data-bind="scope:'voting-scope-testik_122121'"
     class="testik-item"
>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#testik_122121": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "voting-scope-testik_122121": {
                            "component": "Perspective_AsyncCatalog/js/view/products"
                        }
                    }
                }
            }
        }
    </script>
</div>
