<?php
use Perspective\Voting\Block\Widget\Voting;
/** @var Voting $block */

$votingId = $block->getData('voting_id');
$scopeName = 'voting_component';
$votingData = $block->prepareVotingData();
?>
<link rel="stylesheet" type="text/css" href="<?= $block->getViewFileUrl('Perspective_Voting::css/voting.css') ?>">

<div id="custom-component" data-bind="scope:'voting'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#custom-component": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "voting": {
                            "component": "Perspective_Voting/js/view/voting",
                            "votingData": <?= json_encode($votingData) ?>
                        }
                    }
                }
            }
        }
    </script>
</div>
